### ISSUE TITLE
Add possibility to enable / disable Nosto features (feature flags)

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-prestashop#154]
- [x] Toggle SKU tagging
- [ ] Toggle Inventory Level
- [ ] Toggle Product API
- [ ] Toggle Alt. Image URLs
- [ ] Toggle low-stock notifications

**Comment by mridang** [comment]
I don't think we need all the same feature flags as we have on Magento. The Product API should always be used. A lot of Prestashop installations have flaky data. The alt. image URLs is a rather trivial thing to feature-flag. The low-stock notifications don't exist here.
