### ISSUE TITLE
Is the article about bulk-updating products still relevant and accurate?

### ISSUE THREAD

**Issue by mridang** [Nosto/nosto-prestashop#261]
The article about "Updating products in batches" seems to be quite stale and unmaintained so we just want o understand if it is still useful.

According to @chenliangde the PHP process might time-out so would time out.

**Comment by chenliangde** [comment]
There is no an indexer in Prestashop like Magento. It is better to make it part of nosto module if it is needed. The wiki is outdated and it is not working in the 3.X.
