### ISSUE TITLE
Stripping tags from output

### ISSUE THREAD

**Issue by Dh42** [Nosto/nosto-prestashop#299]
**Prestashop version(s) used**: All
**Extension version(s) affected**: 3.7.1

**Description**  
When the description is output on the product page, it is set to hidden, but any tags used in the descriptions are output as well. This is not ideal for SEO and will mess up the flow of the h level tags. Add a strip tags to both the description and short description here, https://github.com/Nosto/nosto-prestashop/blob/develop/classes/models/NostoProduct.php#L53

**How to reproduce**  
Test on a site that has html entered in description or short description while on a product page, examine the hidden nosto meta data. 

**Possible Solution**  
Add strip_tags() around both these outputs. https://github.com/Nosto/nosto-prestashop/blob/develop/classes/models/NostoProduct.php#L53

**Comment by supercid** [comment]
Hi @Dh42,
This is actually a desired behavior for some merchants.
Also, those tags are encoded to avoid XSS, if you inspect the HTML you will see something like this:
![image](https://user-images.githubusercontent.com/2778820/61201467-42d18c80-a6ed-11e9-8188-aba1dabf3a72.png)

If you don't want to render those tags, you can override the extension and add your custom logic. Docs can be found here: https://github.com/Nosto/nosto-prestashop/wiki/Overriding-Product-Data

**Comment by Dh42** [comment]
Even though it is set to display none it still shows up in crawlers. I have fixed it on 3 sites this week from people complaining about the errors showing up in SEM Rush and ahrefs. On the 1.6.x branch the data is not being decoded like your 1.7 example either and is rendering with tags in the descriptions.
