### ISSUE TITLE
Cart footer hook not firing  

### ISSUE THREAD

**Issue by hannunosto** [Nosto/nosto-prestashop#74]
This might be a Prestashop issue as well. Hook shoppingCart has an alias in database but it doesn't get fired. Related to Presta 1.7

**Comment by mridang** [comment]
This seems to be working in the Prestashop 1.7 beta 1 release.

**Comment by mridang** [comment]
The tagging and slots seem to be on all pages. In Prestashop 1.7, the checkout page is locked down and the only hook available is `displayReassurance` found in the file `checkout.tpl`. This page does not extend the default base templates. We assume this is to prevent extensions from messing with the checkout page. We will skip adding any slots and tagging on this page for now.
